In [39]:
#Importamos el dataset brindado!
import pandas as pd
import json
import re 
movies = pd.read_csv('Dataset/movies_dataset.csv')

C:\Users\Pochito\AppData\Local\Temp\ipykernel_7208\3477437770.py:5: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv('Dataset/movies_dataset.csv')

In [40]:
def extraer_datos(df, columna):
    # Función para extraer los valores de una cadena, lista o diccionario
    def extraer_valores(valor):
        if isinstance(valor, str):
            # Si es una cadena, extraer los valores con la expresión regular
            pattern = r"'name': '([^']*)'"
            coincidencias = re.findall(pattern, valor)
            return coincidencias
        elif isinstance(valor, list):
            # Si es una lista, extraer los valores de cada elemento de la lista
            valores = []
            for elemento in valor:
                if 'name' in elemento:
                    valores.append(elemento['name'])
            return valores
        elif isinstance(valor, dict):
            # Si es un diccionario, extraer los valores de la clave 'name'
            if 'name' in valor:
                return valor['name']
        return None
    
    # Aplicar la función a la columna y sobrescribir la columna
    df[columna] = df[columna].apply(extraer_valores)
    
    return df

In [41]:
#mostrar todas las columnas del dataset
pd.set_option('display.max_columns', None)

In [42]:
movies.head(1)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0

In [43]:
extraer_datos(movies, 'belongs_to_collection')
extraer_datos(movies, 'genres')
extraer_datos(movies, 'production_companies')
extraer_datos(movies, 'production_countries')
extraer_datos(movies, 'spoken_languages')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,[Toy Story Collection],30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,[Pixar Animation Studios],[United States of America],1995-10-30,373554033.0,81.0,[English],Released,NaN,Toy Story,False,7.7,5415.0
1,False,None,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[TriStar Pictures, Teitler Film, Interscope Co...",[United States of America],1995-12-15,262797249.0,104.0,"[English, Français]",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,[Grumpy Old Men Collection],0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[Warner Bros., Lancaster Gate]",[United States of America],1995-12-22,0.0,101.0,[English],Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,None,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[Twentieth Century Fox Film Corporation],[United States of America],1995-12-22,81452156.0,127.0,[English],Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,[Father of the Bride Collection],0,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[Sandollar Productions, Touchstone Pictures]",[United States of America],1995-02-10,76578911.0,106.0,[English],Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,None,0,"[Drama, Family]",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,[],[Iran],NaN,0.0,90.0,[فارسی],Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,None,0,[Drama],NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,[Sine Olivia],[Philippines],2011-11-17,0.0,360.0,[],Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,None,0,"[Action, Drama, Thriller]",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,[American World Pictures],[United States of America],2003-08-01,0.0,90.0,[English],Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,None,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,[Yermoliev],[Russia],1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,None,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,[],[United Kingdom],2017-06-09,0.0,75.0,[English],Released,NaN,Queerama,False,0.0,0.0

In [44]:
movies.head(1)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,[Toy Story Collection],30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,[Pixar Animation Studios],[United States of America],1995-10-30,373554033.0,81.0,[English],Released,NaN,Toy Story,False,7.7,5415.0

In [45]:
#Los valores nulos de los campos revenue, budget deben ser rellenados por el número 0
movies['revenue'] = movies['revenue'].fillna(0)
movies['budget'] = movies['budget'].fillna(0)

In [46]:
#contamos los valores nulos de las columnas revenue y budget
movies.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      0
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [47]:
#Los valores nulos del campo release date deben eliminarse.
movies = movies.dropna(subset=['release_date'])

In [48]:
#contamos los valores nulos de release date
movies.isnull().sum()

adult                        0
belongs_to_collection    40888
budget                       0
genres                       0
homepage                 37610
id                           0
imdb_id                     14
original_language           11
original_title               0
overview                   941
popularity                   2
poster_path                339
production_companies         0
production_countries         0
release_date                 0
revenue                      0
runtime                    249
spoken_languages             3
status                      83
tagline                  24981
title                        3
video                        3
vote_average                 3
vote_count                   3
dtype: int64

In [49]:
#De haber fechas, deberán tener el formato AAAA-mm-dd.
movies['release_date'] = pd.to_datetime(movies['release_date'], errors='coerce')

C:\Users\Pochito\AppData\Local\Temp\ipykernel_7208\3597400814.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['release_date'] = pd.to_datetime(movies['release_date'], errors='coerce')

In [50]:
#crear la columna release_year donde extraerán el año de la fecha de estreno.
movies['release_year'] = movies['release_date'].dt.year

C:\Users\Pochito\AppData\Local\Temp\ipykernel_7208\797629494.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['release_year'] = movies['release_date'].dt.year

In [51]:
movies.head(1)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,release_year
0,False,[Toy Story Collection],30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,[Pixar Animation Studios],[United States of America],1995-10-30,373554033.0,81.0,[English],Released,NaN,Toy Story,False,7.7,5415.0,1995.0

In [52]:
#cambiamos el tipo de la columna renueve a int
movies['revenue'] = movies['revenue'].astype(int)

C:\Users\Pochito\AppData\Local\Temp\ipykernel_7208\2633477072.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['revenue'] = movies['revenue'].astype(int)

In [53]:
#remplacer los valores nan de la columna revenue por 0
movies['revenue'] = movies['revenue'].fillna(0)

C:\Users\Pochito\AppData\Local\Temp\ipykernel_7208\1921384664.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['revenue'] = movies['revenue'].fillna(0)

In [54]:
# Reemplazar los valores no numéricos por NaN en la columna 'budget'
movies['budget'] = pd.to_numeric(movies['budget'], errors='coerce')

C:\Users\Pochito\AppData\Local\Temp\ipykernel_7208\783883451.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['budget'] = pd.to_numeric(movies['budget'], errors='coerce')

In [55]:
#cambiamos los valores nulos de la columna budget por 0
movies['budget'] = movies['budget'].fillna(0)

C:\Users\Pochito\AppData\Local\Temp\ipykernel_7208\106303938.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['budget'] = movies['budget'].fillna(0)

In [56]:
#cambiamos el tipo de la columna budget a int
movies['budget'] = movies['budget'].astype(int)

C:\Users\Pochito\AppData\Local\Temp\ipykernel_7208\2878116484.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['budget'] = movies['budget'].astype(int)

In [57]:
movies.dtypes

adult                            object
belongs_to_collection            object
budget                            int32
genres                           object
homepage                         object
id                               object
imdb_id                          object
original_language                object
original_title                   object
overview                         object
popularity                       object
poster_path                      object
production_companies             object
production_countries             object
release_date             datetime64[ns]
revenue                           int32
runtime                         float64
spoken_languages                 object
status                           object
tagline                          object
title                            object
video                            object
vote_average                    float64
vote_count                      float64
release_year                    float64
dtype: object

In [58]:
#Crear la columna con el retorno de inversión, llamada return con los campos revenue y budget, dividiendo estas dos últimas revenue / budget
movies['return'] = movies['revenue'] / movies['budget']

C:\Users\Pochito\AppData\Local\Temp\ipykernel_7208\2336372906.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['return'] = movies['revenue'] / movies['budget']

In [59]:
movies['return'] = movies['return'].fillna(0)

C:\Users\Pochito\AppData\Local\Temp\ipykernel_7208\2974251122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['return'] = movies['return'].fillna(0)

In [60]:
#Eliminar las columnas que no serán utilizadas, video,imdb_id,adult,original_title,vote_count,poster_path y homepage.
movies = movies.drop(['video','imdb_id','adult','original_title','vote_count','poster_path','homepage'], axis=1)

In [61]:
movies.shape

(45379, 19)

In [62]:
movies.head(10)

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,release_year,return
0,[Toy Story Collection],30000000,"[Animation, Comedy, Family]",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,[Pixar Animation Studios],[United States of America],1995-10-30,373554033,81.0,[English],Released,NaN,Toy Story,7.7,1995.0,12.451801
1,None,65000000,"[Adventure, Fantasy, Family]",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"[TriStar Pictures, Teitler Film, Interscope Co...",[United States of America],1995-12-15,262797249,104.0,"[English, Français]",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,1995.0,4.043035
2,[Grumpy Old Men Collection],0,"[Romance, Comedy]",15602,en,A family wedding reignites the ancient feud be...,11.7129,"[Warner Bros., Lancaster Gate]",[United States of America],1995-12-22,0,101.0,[English],Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,1995.0,0.000000
3,None,16000000,"[Comedy, Drama, Romance]",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,[Twentieth Century Fox Film Corporation],[United States of America],1995-12-22,81452156,127.0,[English],Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,1995.0,5.090760
4,[Father of the Bride Collection],0,[Comedy],11862,en,Just when George Banks has recovered from his ...,8.387519,"[Sandollar Productions, Touchstone Pictures]",[United States of America],1995-02-10,76578911,106.0,[English],Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,1995.0,inf
5,None,60000000,"[Action, Crime, Drama, Thriller]",949,en,"Obsessive master thief, Neil McCauley leads a ...",17.924927,"[Regency Enterprises, Forward Pass, Warner Bros.]",[United States of America],1995-12-15,187436818,170.0,"[English, Español]",Released,A Los Angeles Crime Saga,Heat,7.7,1995.0,3.123947
6,None,58000000,"[Comedy, Romance]",11860,en,An ugly duckling having undergone a remarkable...,6.677277,"[Paramount Pictures, Scott Rudin Productions, ...","[Germany, United States of America]",1995-12-15,0,127.0,"[Français, English]",Released,You are cordially invited to the most surprisi...,Sabrina,6.2,1995.0,0.000000
7,None,0,"[Action, Adventure, Drama, Family]",45325,en,"A mischievous young boy, Tom Sawyer, witnesses...",2.561161,[Walt Disney Pictures],[United States of America],1995-12-22,0,97.0,"[English, Deutsch]",Released,The Original Bad Boys.,Tom and Huck,5.4,1995.0,0.000000
8,None,35000000,"[Action, Adventure, Thriller]",9091,en,International action superstar Jean Claude Van...,5.23158,"[Universal Pictures, Imperial Entertainment, S...",[United States of America],1995-12-22,64350171,106.0,[English],Released,Terror goes into overtime.,Sudden Death,5.5,1995.0,1.838576
9,[James Bond Collection],58000000,"[Adventure, Action, Thriller]",710,en,James Bond must unmask the mysterious head of ...,14.686036,"[United Artists, Eon Productions]","[United Kingdom, United States of America]",1995-11-16,352194034,130.0,"[English, Pусский, Español]",Released,No limits. No fears. No substitutes.,GoldenEye,6.6,1995.0,6.072311

In [63]:
#cramos la columna release_month donde extraerán el mes de la fecha de estreno.
movies['release_month'] = movies['release_date'].dt.month

In [64]:
#cremos la columna release_day donde extraerán el dia de la fecha de estreno.
movies['release_day'] = movies['release_date'].dt.day

In [65]:
#creamos una colunma que obtenga el dia historicamente de la columna release_date
movies['release_dayofweek'] = movies['release_date'].dt.dayofweek

In [66]:
movies.head(3)

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,release_year,return,release_month,release_day,release_dayofweek
0,[Toy Story Collection],30000000,"[Animation, Comedy, Family]",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,[Pixar Animation Studios],[United States of America],1995-10-30,373554033,81.0,[English],Released,NaN,Toy Story,7.7,1995.0,12.451801,10.0,30.0,0.0
1,None,65000000,"[Adventure, Fantasy, Family]",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"[TriStar Pictures, Teitler Film, Interscope Co...",[United States of America],1995-12-15,262797249,104.0,"[English, Français]",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,1995.0,4.043035,12.0,15.0,4.0
2,[Grumpy Old Men Collection],0,"[Romance, Comedy]",15602,en,A family wedding reignites the ancient feud be...,11.7129,"[Warner Bros., Lancaster Gate]",[United States of America],1995-12-22,0,101.0,[English],Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,1995.0,0.000000,12.0,22.0,4.0

In [67]:
#eliminamos valores nulos de la columna title
movies = movies.dropna(subset=['title'])

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,release_year,return,release_month,release_day,release_dayofweek
0,[Toy Story Collection],30000000,"[Animation, Comedy, Family]",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,[Pixar Animation Studios],[United States of America],1995-10-30,373554033,81.0,[English],Released,NaN,Toy Story,7.7,1995.0,12.451801,10.0,30.0,0.0

In [ ]:
movies.isnull().sum()

In [68]:
#convertimos todo el dataframe en minusculas para poder hacer busquedas
movies = movies.apply(lambda x: x.astype(str).str.lower())

In [69]:
def eliminar_corchetes_comillas(df, columna):
    # Función para eliminar los corchetes y comillas de una columna
    df[columna] = df[columna].apply(lambda x: str(x).replace('[', '').replace(']', '').replace('"', '').replace("'", ""))
    return df

In [70]:
eliminar_corchetes_comillas(movies, 'belongs_to_collection')
eliminar_corchetes_comillas(movies, 'genres')
eliminar_corchetes_comillas(movies, 'production_companies')
eliminar_corchetes_comillas(movies, 'production_countries')
eliminar_corchetes_comillas(movies, 'spoken_languages')

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,release_year,return,release_month,release_day,release_dayofweek
0,toy story collection,30000000,"animation, comedy, family",862,en,"led by woody, andy's toys live happily in his ...",21.946943,pixar animation studios,united states of america,1995-10-30,373554033,81.0,english,released,nan,toy story,7.7,1995.0,12.4518011,10.0,30.0,0.0
1,none,65000000,"adventure, fantasy, family",8844,en,when siblings judy and peter discover an encha...,17.015539,"tristar pictures, teitler film, interscope com...",united states of america,1995-12-15,262797249,104.0,"english, français",released,roll the dice and unleash the excitement!,jumanji,6.9,1995.0,4.0430346,12.0,15.0,4.0
2,grumpy old men collection,0,"romance, comedy",15602,en,a family wedding reignites the ancient feud be...,11.7129,"warner bros., lancaster gate",united states of america,1995-12-22,0,101.0,english,released,still yelling. still fighting. still ready for...,grumpier old men,6.5,1995.0,0.0,12.0,22.0,4.0
3,none,16000000,"comedy, drama, romance",31357,en,"cheated on, mistreated and stepped on, the wom...",3.859495,twentieth century fox film corporation,united states of america,1995-12-22,81452156,127.0,english,released,friends are the people who let you be yourself...,waiting to exhale,6.1,1995.0,5.09075975,12.0,22.0,4.0
4,father of the bride collection,0,comedy,11862,en,just when george banks has recovered from his ...,8.387519,"sandollar productions, touchstone pictures",united states of america,1995-02-10,76578911,106.0,english,released,just when his world is back to normal... he's ...,father of the bride part ii,5.7,1995.0,inf,2.0,10.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45460,none,0,"drama, action, romance",30840,en,"yet another version of the classic epic, with ...",5.683753,"westdeutscher rundfunk (wdr), working title fi...","canada, germany, united kingdom, united states...",1991-05-13,0,104.0,english,released,nan,robin hood,5.7,1991.0,0.0,5.0,13.0,0.0
45462,none,0,drama,111109,tl,an artist struggles to finish his work while a...,0.178241,sine olivia,philippines,2011-11-17,0,360.0,,released,nan,century of birthing,9.0,2011.0,0.0,11.0,17.0,3.0
45463,none,0,"action, drama, thriller",67758,en,"when one of her hits goes wrong, a professiona...",0.903007,american world pictures,united states of america,2003-08-01,0,90.0,english,released,a deadly game of wits.,betrayal,3.8,2003.0,0.0,8.0,1.0,4.0
45464,none,0,,227506,en,"in a small town live two brothers, one a minis...",0.003503,yermoliev,russia,1917-10-21,0,87.0,,released,nan,satan triumphant,0.0,1917.0,0.0,10.0,21.0,6.0
45465,none,0,,461257,en,50 years after decriminalisation of homosexual...,0.163015,,united kingdom,2017-06-09,0,75.0,english,released,nan,queerama,0.0,2017.0,0.0,6.0,9.0,4.0

In [71]:

movies.head(1)

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,release_year,return,release_month,release_day,release_dayofweek
0,toy story collection,30000000,"animation, comedy, family",862,en,"led by woody, andy's toys live happily in his ...",21.946943,pixar animation studios,united states of america,1995-10-30,373554033,81.0,english,released,nan,toy story,7.7,1995.0,12.4518011,10.0,30.0,0.0

In [72]:
#cambiamos el tipo de datos a float
movies['revenue'] = movies['revenue'].astype(float)
movies['budget'] = movies['budget'].astype(float)

In [73]:
movies.dtypes

belongs_to_collection     object
budget                   float64
genres                    object
id                        object
original_language         object
overview                  object
popularity                object
production_companies      object
production_countries      object
release_date              object
revenue                  float64
runtime                   object
spoken_languages          object
status                    object
tagline                   object
title                     object
vote_average              object
release_year              object
return                    object
release_month             object
release_day               object
release_dayofweek         object
dtype: object

In [74]:
#guardamos el nuevo dataset
movies.to_csv('Dataset/movies_dataset_trabajado.csv', index=False)

In [76]:
movies['title'].isnull().sum()

0